server:
  port: 10086
spring:
  application:
    name: demo-registry
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka #请换成自己的ip
    register-with-eureka: false #不注册
    fetch-registry: false #不拉取服务列表
  server:
    eviction-interval-timer-in-ms: 10000 #5秒 剔除无效连接的间隔时间
    enable-replicated-request-compression: false #关闭自我保护状态

